version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: jamespatten1996@gmail.com
        PGADMIN_DEFAULT_PASSWORD: devpassword
    volumes:
        - pgadmin:/var/lib/pgadmin/data
    ports:
        - "8001:80"
    logging:
        driver: none

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "canopact.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/canopact'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A canopact.blueprints.contact.tasks 
    env_file:
      - '.env'
    volumes:
      - '.:/canopact'

  celery_beat:
    build: .
    command: celery beat -l info -A canopact.blueprints.contact.tasks -S redbeat.RedBeatScheduler 
    env_file:
    - '.env'
    volumes:
    - '.:/canopact'


volumes:
  postgres:
  redis:
  pgadmin: